### ISSUE TITLE
Cannot read property 'defaultView' of undefined

### ISSUE THREAD

**Issue by hjywyj** [antvis/wx-f2#132]
peError: Cannot read property 'defaultView' of undefined
    at Object.getStyle (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:1532:61)
    at Object.getWidth (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:1534:22)
    at t.e._initCanvas (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:2152:47)
    at new t (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:2136:96)
    at e.n._initCanvas (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:763:19)
    at e.n._init (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:770:24)
    at new e (http://127.0.0.1:41998/appservice/f2-canvas/lib/f2.js:652:15)
    at

**Comment by simaQ** [comment]
https://github.com/antvis/f2-canvas#%E9%97%AE%E9%A2%98-1
