### ISSUE TITLE
小程序不支持 showXTip

### ISSUE THREAD

**Issue by DiamondYuan** [antvis/wx-f2#150]
版本:wx-f2 master 分支代码 把 pages/line/index.js 替换成下面的代码

错误堆栈
```
thirdScriptError
Cannot read property 'defaultView' of undefined;at undefined page touchStart function
TypeError: Cannot read property 'defaultView' of undefined
    at Object.getStyle (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:1980:65)
    at Object.getHeight (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:1984:26)
    at t.e.setXTipPosition (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:3869:25)
    at t.e._setTooltip (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:3732:45)
    at t.e.showTooltip (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:3770:50)
    at t.e.handleShowEvent (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:3781:57)
    at e.i (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:62:19)
    at e.c.emitEvent (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/wx-f2/index.js:1936:90)
    at V.touchStart (http://127.0.0.1:23594/appservice/miniprogram_npm/@antv/f2-canvas/index.js:187:23)
    at V.D (http://127.0.0.1:23594/appservice/__dev__/WAService.js:1:676510)
```

错误原因 使用了 document
```
 return t.currentStyle ? t.currentStyle[e] : document.defaultView.getComputedStyle(t, null).getPropertyValue(e)
```

```
let chart = null;

function initChart(canvas, width, height, F2) {
  const data = [{
    date: "2017-06-05",
    value: 116
  }, {
    date: "2017-06-06",
    value: 129
  }, {
    date: "2017-06-07",
    value: 135
  }, {
    date: "2017-06-08",
    value: 86
  }, {
    date: "2017-06-09",
    value: 73
  }, {
    date: "2017-06-10",
    value: 85
  }, {
    date: "2017-06-11",
    value: 73
  }, {
    date: "2017-06-12",
    value: 68
  }, {
    date: "2017-06-13",
    value: 92
  }, {
    date: "2017-06-14",
    value: 130
  }, {
    date: "2017-06-15",
    value: 245
  }, {
    date: "2017-06-16",
    value: 139
  }, {
    date: "2017-06-17",
    value: 115
  }, {
    date: "2017-06-18",
    value: 111
  }, {
    date: "2017-06-19",
    value: 309
  }, {
    date: "2017-06-20",
    value: 206
  }, {
    date: "2017-06-21",
    value: 137
  }, {
    date: "2017-06-22",
    value: 128
  }, {
    date: "2017-06-23",
    value: 85
  }, {
    date: "2017-06-24",
    value: 94
  }, {
    date: "2017-06-25",
    value: 71
  }, {
    date: "2017-06-26",
    value: 106
  }, {
    date: "2017-06-27",
    value: 84
  }, {
    date: "2017-06-28",
    value: 93
  }, {
    date: "2017-06-29",
    value: 85
  }, {
    date: "2017-06-30",
    value: 73
  }, {
    date: "2017-07-01",
    value: 83
  }, {
    date: "2017-07-02",
    value: 125
  }, {
    date: "2017-07-03",
    value: 107
  }, {
    date: "2017-07-04",
    value: 82
  }, {
    date: "2017-07-05",
    value: 44
  }, {
    date: "2017-07-06",
    value: 72
  }, {
    date: "2017-07-07",
    value: 106
  }, {
    date: "2017-07-08",
    value: 107
  }, {
    date: "2017-07-09",
    value: 66
  }, {
    date: "2017-07-10",
    value: 91
  }, {
    date: "2017-07-11",
    value: 92
  }, {
    date: "2017-07-12",
    value: 113
  }, {
    date: "2017-07-13",
    value: 107
  }, {
    date: "2017-07-14",
    value: 131
  }, {
    date: "2017-07-15",
    value: 111
  }, {
    date: "2017-07-16",
    value: 64
  }, {
    date: "2017-07-17",
    value: 69
  }, {
    date: "2017-07-18",
    value: 88
  }, {
    date: "2017-07-19",
    value: 77
  }, {
    date: "2017-07-20",
    value: 83
  }, {
    date: "2017-07-21",
    value: 111
  }, {
    date: "2017-07-22",
    value: 57
  }, {
    date: "2017-07-23",
    value: 55
  }, {
    date: "2017-07-24",
    value: 60
  }];

  chart = new F2.Chart({
    el: canvas,
    width,
    height
  });

  chart.source(data, {
    value: {
      tickCount: 5,
      min: 0
    },
    date: {
      type: 'timeCat',
      range: [0, 1],
      tickCount: 3
    }
  });

  chart.tooltip({
    custom: true,
    showXTip: true,
    showYTip: true,
    snap: true,
    crosshairsType: 'xy',
    crosshairsStyle: {
      lineDash: [2]
    }
  });
  chart.axis('date', {
    label: function label(text, index, total) {
      var textCfg = {};
      if (index === 0) {
        textCfg.textAlign = 'left';
      } else if (index === total - 1) {
        textCfg.textAlign = 'right';
      }
      return textCfg;
    }
  });
  chart.line().position('date*value');
  chart.render();
  return chart;
}

Page({
  onShareAppMessage: function (res) {
    return {
      title: 'F2 微信小程序图表组件，你值得拥有~',
      path: '/pages/index/index',
      success: function () { },
      fail: function () { }
    }
  },
  data: {
    opts: {
      onInit: initChart
    }
  },

  onReady() {
  }
});
```

**Comment by simaQ** [comment]
3.3.x 新增的功能并不保证能够全部兼容小程序
