### ISSUE TITLE
f2更新到3.2.0-beta.5报错

### ISSUE THREAD

**Issue by ll929** [antvis/wx-f2#24]
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'createElement' of undefined 
 TypeError: Cannot read property 'createElement' of undefined
    at http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:4307:17
    at Object.<anonymous> (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:4568:6)
    at e (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:10:93)
    at Object.<anonymous> (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:2611:13)
    at e (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:10:93)
    at Object.<anonymous> (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:4096:32)
    at e (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:10:93)
    at Object.<anonymous> (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:4094:78)
    at e (http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:10:93)
    at http://127.0.0.1:61712/appservice/static/f2-canvas/lib/f2.js:21:18
console.error @ VM114:1
(anonymous) @ WAService.js:5
(anonymous) @ WAService.js:6
a @ appservice?t=1529628824674:1171
window.onerror @ VM114:1
VM114:1 jsEnginScriptError
Component is not found in path "static/f2-canvas/f2-canvas" (using by "pages/analysis/main")
Error: Component is not found in path "static/f2-canvas/f2-canvas" (using by "pages/analysis/main")
    at e (http://127.0.0.1:61712/appservice/__dev__/WAService.js:18:7261)
    at e (http://127.0.0.1:61712/appservice/__dev__/WAService.js:18:7413)
    at oe (http://127.0.0.1:61712/appservice/__dev__/WAService.js:18:16573)
    at Object.t.addView (http://127.0.0.1:61712/appservice/__dev__/WAService.js:18:17894)
    at Function.value (http://127.0.0.1:61712/appservice/__dev__/WAService.js:1:29486)
    at B (http://127.0.0.1:61712/appservice/__dev__/WAService.js:1:6091)
    at K (http://127.0.0.1:61712/appservice/__dev__/WAService.js:1:8527)
    at q (http://127.0.0.1:61712/appservice/__dev__/WAService.js:1:8793)
    at Function.<anonymous> (http://127.0.0.1:61712/appservice/__dev__/WAService.js:1:11643)
    at http://127.0.0.1:61712/appservice/__dev__/WAService.js:1:17558
console.error @ VM114:1
errorReport @ WAService.js:4
(anonymous) @ WAService.js:4
t.errorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:7
(anonymous) @ WAService.js:7
(anonymous) @ WAService.js:6
a @ appservice?t=1529628824674:1171
d.registerCallback @ appservice?t=1529628824674:1171
m.forEach @ appservice?t=1529628824674:1171
d @ appservice?t=1529628824674:1171
j.onmessage @ appservice?t=1529628824674:1171

**Comment by SeanWangDev** [comment]
对的，一起踩坑。主要原因是3.2里面针对多点触碰的hammerjs中的界面操作主要还是基于document。而小程序是不支持document的。

**Comment by simaQ** [comment]
恩，是这样的，F2 3.2.0 beta 版本新增的交互基于 hammer.js 的手势事件，默认环境是 H5，还咩有做小程序环境的适配。

**Comment by yuzexing** [comment]
手势实践持续关注中
